### ISSUE TITLE
There are breaking changes in versions 1.2.4 or 1.2.5!

### ISSUE THREAD

**Issue by alekzuz** [izzyumkin/EmojiPicker#55]

**Comment by sven0311** [comment]
I get the following error after updating from 1.2.3 to 1.2.5:

`MCEmojiPicker/MCUnicodeManager.swift:114: Fatal error: Failed to load emoji resource`

Do you mean the same?
